# This rule is not used by the project persys-operator-k8s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the prow.persys.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: persys-operator-k8s
    app.kubernetes.io/managed-by: kustomize
  name: persysoperator-editor-role
rules:
- apiGroups:
  - prow.persys.io
  resources:
  - persysoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prow.persys.io
  resources:
  - persysoperators/status
  verbs:
  - get
