# permissions for end users to edit persysclouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: persyscloud-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: persys-operator-k8s
    app.kubernetes.io/part-of: persys-operator-k8s
    app.kubernetes.io/managed-by: kustomize
  name: persyscloud-editor-role
rules:
- apiGroups:
  - cloud-api.persys.io
  resources:
  - persysclouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-api.persys.io
  resources:
  - persysclouds/status
  verbs:
  - get
