---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloud-api.persys.io
  resources:
  - persysclouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-api.persys.io
  resources:
  - persysclouds/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-api.persys.io
  resources:
  - persysclouds/status
  verbs:
  - get
  - patch
  - update
